name: mizyaliapp
description: It is an application to manage watering.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts:
  flutter_svg: ^0.17.4
  charts_flutter: ^0.9.0
  flutter_calendar_carousel: ^1.4.12
  image_picker: ^0.6.7+3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # splash
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  #image: assets/icons/plant.png
  color: "E0E5EC"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

